### ISSUE TITLE
水波球锯齿

### ISSUE THREAD

**Issue by William-Cai** [zedwang/waterball#1]
水波球上，如果波动后，内圈圆的会留下一个有锯齿的图像问题？如何解决？

**Comment by William-Cai** [comment]
动态更新数据到100%后，重新setOptions("value", ++count)后，又开始重新。会导致内圈又个锯齿点的颜色圈

**Comment by zedwang** [comment]
@githubwinnie 那个是因为波浪的波峰和波谷太大，你可以把波浪的高度设置小一点，就不会了

**Comment by William-Cai** [comment]
![image](https://user-images.githubusercontent.com/17944714/29544910-d22da342-871d-11e7-9498-15850e3e9891.png)
麻烦看下，这种情况导致的原因

**Comment by zedwang** [comment]
@githubwinnie    感谢！已提交
